version: "3.9"
services:
  tf-container:
    build: .
    volumes:
      - ../backend/:/backend
    networks:
        cortexgroove-storage:
          ipv4_address: 172.16.238.4
  storage:
    image: postgres:latest
    networks:
      cortexgroove-storage:
        ipv4_address: 172.16.238.2
    restart: always
    environment:
      POSTGRES_PASSWORD: temp_dev_password
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  storage-client:
    image: dpage/pgadmin4:latest
    user: "0"
    networks:
      cortexgroove-storage:
        ipv4_address: 172.16.238.3
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: temp_dev_password
    volumes:
      - ./pgadmin:/var/lib/pgadmin
networks:
  cortexgroove-storage:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24